### ISSUE TITLE
Tutorial 1 - Setting up for collaborating on an existing GitHub repository

### ISSUE THREAD

**Issue by joeflack4** [joeflack4/ppp-training-fork#1]
### 1. Fork the repo
 - This is done manually in GitHub, at top right of the screen on the repo's home page.

### 2. Clone your fork of the repo
 - `git clone <url>`
- You can find the "<url>" by clicking "clone or download" at the top right of the screen on the repo's home page.

### 3. Add remotes
A remote is a link to another copy of the repository, such as your repository on GitHub, or an upstream repository (such as the one you forked it from). There is also a notion called "trunk". Think of the trunk of a tree. The "trunk" repository is the first repository of any project, before any forks, or forks of forks, were created.
By default, when cloning from GitHub, you will automatically get 1 remote, called "origin", which links the repo on your local machine to the one on GitHub. Other remotes must be added manually.
- View a list of names for all your remotes: `git remote`
- View with more info (verbosely), such as url: `git remote -v`
- Add a remote: `git remote add <remote-name> <url>`
  - Remote name is up to you, but it is a good idea to use a conventional name, such as "trunk", "upstream", or the name of the repo owner.
  - URL can be found by going to the repo you want to add and clicking the "clone or download" button.
- Fetching
Even though you've added your remotes, you haven't locally downloaded any information from those remote repositories, such as the branches that exist and their code. To get this information, you can use `git fetch`.
  - Fetch all branches in all remotes: `git fetch --all`

### 4. Check out the branches you want to have a local copy of
By default, when you clone or fork, you will only get 1 branch--the one that is set as the default branch on the repo, which, by default, is "master".
- View all of your local branches: `git branch`
- View all branches on all remotes you have added: `git branch --all`
- Add a branch from a remote: `git checkout <remote-name>/<branch-name> && git checkout -b <branch-name>`
  - Example: `git checkout trunk/develop`, then `git checkout -b develop`
  - The `-b` flag tells git that you want to create a local branch. Otherwise, it will not create a branch; it will just let you check out the branch temporarily.
- Add a new branch based on one of your local branches: `git checkout -b <branch-name>
  - There is a concept called a "feature branch". This is ideally where all of your changes related to a single topic should be located. By "topic" I mean that a feature branch is not necessarily just used when creating a new feature--it is also used when making a general update to something pre-existing, or also when applying a bug fix. At PMA2020, we use a special workflow. We have a "master" branch which matches what is on the production server. We have a "develop" branch that is pre-production. All collaborators make their own individual changes in individual feature branches, and then those are merged in / pull requested into the develop branch. When the develop branch is stable and ready for a new release, it is merged into master.
- Change branches: `git checkout <branch-name>`

## Tasks
- [ ] Fork and clone this repo.
- [ ] Add this original repo as a remote, named "trunk".
- [ ] Add remotes of other collaborators. (if applicable)
- [ ] Check out a local copy of the "develop" branch of this repo.
- [ ] Make a feature branch off of that repo.
